name: Build and Deploy Documentation

on:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'
      - 'popexposure/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: 
      - main
    paths:
      - 'docs/**'
      - 'popexposure/**'
      - 'mkdocs.yml'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/python-poetry-env
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper git info

      - name: Configure Git for mkdocs
        shell: bash -l {0}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Build documentation
        shell: bash -l {0}
        run: poetry run mkdocs build --clean --verbose

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4