name: Build and Deploy Documentation

on:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'
      - 'popexposure/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: 
      - main
    paths:
      - 'docs/**'
      - 'popexposure/**'
      - 'mkdocs.yml'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper git info

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.11'
          miniforge-version: latest
          activate-environment: docs
          use-mamba: true

      - name: Install GDAL via conda
        shell: bash -l {0}
        run: |
          conda install -c conda-forge gdal geopandas rasterio

      - name: Install documentation dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          # Install all mkdocs dependencies explicitly
          pip install mkdocs>=1.5.0
          pip install mkdocs-material>=9.0.0
          pip install mkdocs-jupyter>=0.24.0
          pip install mkdocstrings[python]>=0.20.0
          pip install pymdown-extensions>=10.0.0
          # Then install your package
          pip install -e .
          # Verify everything is installed
          mkdocs --version
          python -c "import mkdocs_jupyter; print('mkdocs-jupyter installed successfully')"

      - name: Configure Git for mkdocs
        shell: bash -l {0}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Build documentation
        shell: bash -l {0}
        run: mkdocs build --clean --verbose

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Debug mkdocs-jupyter
        shell: bash -l {0}
        run: |
          echo "=== Python packages ==="
          pip list | grep -E "(mkdocs|jupyter|nbconvert)"
          echo "=== Testing notebook rendering ==="
          python -c "
          import mkdocs_jupyter
          import nbconvert
          print('mkdocs-jupyter version:', mkdocs_jupyter.__version__)
          print('nbconvert version:', nbconvert.__version__)
          "
          echo "=== Checking notebook file ==="
          ls -la demo/demo_code/01_demo_data_setup.ipynb
          head -5 demo/demo_code/01_demo_data_setup.ipynb

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4